### ISSUE TITLE
Simply loading AutoRemoveColumns seems to interfere with DBICs group_by inferrence

### ISSUE THREAD

**Issue by ribasushi** [frioux/DBIx-Class-Helpers#83]
```
~dbic_repo$ perl -Ilib -It/lib -MDBICTest -MDevel::Dwarn -e '
  Dwarn [ DBICTest->init_schema
                   ->resultset("Artist")
                    ->search({}, { group_by => "name" })
                     ->count_rs
                      ->as_query ]
'
```
vs
```
~dbic_repo$ perl -Ilib -It/lib -MDBICTest -MDevel::Dwarn -e '
  require DBICTest::BaseResultSet;
  DBICTest::BaseResultSet->load_components("Helper::ResultSet::AutoRemoveColumns");
  Dwarn [ DBICTest->init_schema
                   ->resultset("Artist")
                    ->search({}, { group_by => "name" })
                     ->count_rs
                      ->as_query ]
'
```

P.S. This is the problem with http://lists.scsys.co.uk/pipermail/dbix-class/2017-October/012682.html, user has already been informed about this issue.

**Comment by melnik13** [comment]
Thanks a lot!

**Comment by ribasushi** [comment]
Had a moment to look: @frioux the problem [is here](https://github.com/frioux/DBIx-Class-Helpers/blob/1445098fc/lib/DBIx/Class/Helper/ResultSet/RemoveColumns.pm#L15). You must check for presence of a `select` as a reset in addition to `columns`

**Comment by ribasushi** [comment]
@melnik13 this is an easy fix, I am pretty sure @frioux would appreciate a PR with a test similar to what I showed above.

**Comment by melnik13** [comment]
Aye, the test is ready, the PR has been submitted!

**Comment by frioux** [comment]
Fixed, will release after testing on travis.

**Comment by frioux** [comment]
FYI I keep coming back to this and running into stupid unrelated problems.
Apparently there were enough environmental changes since my last helpers
release that I can't pass my own stress tests 😢 anyway not forgotten, just
slow progress

-- 
Sent from a rotary phone rented from Ma Bell

On Oct 10, 2017 9:11 PM, "Vladimir Melnik" <notifications@github.com> wrote:

Aye, the test is ready, the PR has been submitted!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/frioux/DBIx-Class-Helpers/issues/83#issuecomment-335677012>,
or mute the thread

**Comment by frioux** [comment]
Finally got tests passing on travis.  I am going to give myself 30m when my kid is taking a nap to try to roll in some other fixes and features, and the cut bait and release this.
